name: master

on:
  push:
    branches: [ main, develop, ci/cd ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-master-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Setting .env.production
        run: |
          echo "REACT_APP_SERVER_ADDRESS=$REACT_APP_SERVER_ADDRESS" >> .env.production
          echo "REACT_APP_PRODUCTION=$REACT_APP_PRODUCTION" >> .env.production
          cat .env.production
        env:
          REACT_APP_SERVER_ADDRESS: ${{ secrets.REACT_APP_SERVER_ADDRESS }}
          REACT_APP_PRODUCTION: ${{ secrets.REACT_APP_PRODUCTION }}

      - name: Install Dependencies
        working-directory: ./frontend
        run: yarn install
        
      - name: Build...
        working-directory: ./frontend
        run: CI=false npm run build
        
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: "codetree.com"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-northeast-2"
          SOURCE_DIR: "build"
